### PR TITLE
derive Key

### LINKED ISSUE #106: Add deriveable support for structs as View keys
This request is a refinement of the idea from #65. View Keys need to be able to be compared on a byte-by-byte basis and resolve order, and the Key trait currently must be manually implemented for any non-integer types.

This should be done as a custom derive. The composite format should be lightweight and focus on the problems that multi-field comparisons might unveil -- e.g., a String key is variable length, and a shorter String should sort lower than a longer string, regardless of the bytes that follow in the next field.

The other thing a custom derive can do is offer the ability to support floating points. As far as I can come up with, there's not a reliable way to encode a floating point number such that it can be memcmp'ed. An attribute could be used to allow multiple strategies for utilizing a floating point key -- e.g., optionally multiply by 10^x then convert to a i64/u64.

The macro needs to be able to have the location of `bonsaidb_core` specified as an optional attribute. By default, it should use `::bonsaidb::core` as the path to bonsaidb_core, but a user should be able to override it based on their usage. E.g., `#[view(core = bonsaidb_server::core)]`.

### PR DESCRIPTION
**Pull request by ModProg**
fixes #106

### CODE REVIEW

**Comment by ModProg** [comment]
@ecton It is probably a good idea, if you run `cargo expand --test key` and have a read of what the macro produces.

**Comment by ModProg** [comment]
also feel free to suggest some actual tests :D

**Comment by ecton** [comment]
Just wanted to say thank you for getting this submitted. I started feeling a little under the weather this afternoon, so I'll check this out soon but it'll be at least tomorrow.

**Comment by ecton** [comment]
This all looks great. As for real tests, I would look at #240 for example of two values being encoded that produces an interesting edge case and uses two datatypes. I wouldn't worry too much about thorough testing -- the main test the macro needs to worry about it to ensure every bit of data is encoded. The testing of the composite key encoding/decoding can be handled independently, as long as we are confident in the unit tests calling the encoding/decoding functions in the proper order.

There are some changes in main that hopefully will clean up some of the ugliness from the return types in decode_composite_key. I've deprecated encode/decode_composite_key in favor of two structs: CompositeKeyEncoder, CompositeKeyDecoder. An example usage:

```rust
 let value1 = String::from("hello");
 let value2 = 42_u32;
 let mut encoder = CompositeKeyEncoder::default();
 encoder.encode(&value1).unwrap();
 encoder.encode(&value2).unwrap();
 let encoded = encoder.finish();
 
 let mut decoder = CompositeKeyDecoder::new(&encoded);
 let decoded_string = decoder.decode::<String>().unwrap();
 assert_eq!(decoded_string, value1);
 let decoded_u32 = decoder.decode::<u32>().unwrap();
 assert_eq!(decoded_u32, value2);
 decoder.finish().expect("trailing bytes");
```

The last thing is to add one more option to the derive macro: `allow_null_bytes = true`. By default this should be false. When this is set, call `CompositeKeyEncoder::allow_null_bytes_in_variable_fields`. This relaxes a restriction that might be irrelevant for many users, but should be enabled by default to avoid the appearance of bugs.

**Comment by ModProg** [comment]
@ecton I added the new encoder/decoder and some test.

**Comment by ecton** [comment]
Thank you as always @ModProg!

**Pull request merged**
